options:
  # This is probably not a config option that's worth exposing, and it would be better to just
  # configure Exim in a way that's appropriate to any of these uses (and perhaps just allow
  # specifying if external connections should be accepted).
  config-type:
    default: "internet"
    description: Wrapper for the Debian configuration type; for example - internet, smarthost, local
    type: string
  hostnames:
    default: ""
    description: A comma-separated list of domains for which we should consider ourselves the final destination.
    type: string
