options:
  primary-hostname:
    default: ""
    description: The primary name of the email server. If not set, Exim will use the system's FQDN.
    type: string
  extra-hostnames:
    default: ""
    description: A comma-separated list of domains for which we should consider ourselves the final destination.
    type: string
